# Generated by Django 4.2.7 on 2023-11-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_file',
            field=models.FileField(upload_to='F:\\Desktop\\batvoice\\miniprojet\\audio'),
        ),
    ]
