# Generated by Django 4.2.7 on 2023-11-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_alter_audiodata_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
