# Generated by Django 4.2.7 on 2023-11-06 14:42

from django.db import migrations, models
import mini.models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_alter_audiodata_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodata',
            name='audio_file',
            field=models.FileField(upload_to=mini.models.audio_directory_path),
        ),
    ]
