# Generated by Django 4.2.7 on 2023-11-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0015_remove_transcription_annotator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='annotator',
        ),
    ]
