# Generated by Django 4.2.7 on 2023-11-06 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mini', '0017_transcription_annotator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='annotator',
        ),
        migrations.AddField(
            model_name='transcription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
