# Generated by Django 4.2.7 on 2023-11-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0020_alter_transcription_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters', models.CharField(max_length=200)),
            ],
        ),
    ]
